// ============================================================
// Monster & Action Data for MVP
// ============================================================

// Sensory axes: sound, temperature, smell, behavior
// Each action targets one axis with a value

export const SENSORY_AXES = ['sound', 'temperature', 'smell', 'behavior'];

// Ally monsters (3 allies, 3 actions each)
export const ALLY_MONSTERS = [
  {
    id: 'water',
    name: '이슬요정',
    img: 'asset/monsters/water_ally.png',
    devolvedImg: 'asset/monsters/water_devolved.png',
    desc: '잔잔한 물방울을 다루는 온화한 요정',
    hp: 30,
    maxHp: 30,
    xp: 0,
    xpThreshold: 5,
    inEgg: false,
    devolved: false,
    devolvedName: '물방울콩',
    devolvedDesc: '아주 작고 투명한 콩 모양의 존재',
    actions: [
      { id: 'rain_sound',    name: '빗소리',       axis: 'sound',       power: 12, escapeRisk: 2,  log: '잔잔한 빗소리가 주변에 퍼진다.' },
      { id: 'cool_mist',     name: '서늘한 안개',  axis: 'temperature', power: 10, escapeRisk: 3,  log: '서늘한 안개가 천천히 감싼다.' },
      { id: 'keep_distance', name: '거리 유지',    axis: 'behavior',    power: 8,  escapeRisk: -5, log: '조용히 거리를 유지하며 지켜본다.' },
    ],
  },
  {
    id: 'fire',
    name: '숯뭉이',
    img: 'asset/monsters/fire_ally.png',
    devolvedImg: 'asset/monsters/fire_devolved.png',
    desc: '따뜻한 온기를 품은 작은 불씨 생물',
    hp: 25,
    maxHp: 25,
    xp: 0,
    xpThreshold: 5,
    inEgg: false,
    devolved: false,
    devolvedName: '꺼지지않는불씨',
    devolvedDesc: '손바닥 위에 올라오는 아주 작은 불씨',
    actions: [
      { id: 'warm_aura',     name: '따뜻한 온기',    axis: 'temperature', power: 12, escapeRisk: 2,  log: '포근한 온기가 살며시 전해진다.' },
      { id: 'gentle_glow',   name: '은은한 존재감',  axis: 'behavior',    power: 10, escapeRisk: 1,  log: '은은한 빛으로 존재를 알린다.' },
      { id: 'slow_approach', name: '천천히 접근',    axis: 'behavior',    power: 14, escapeRisk: 6,  log: '아주 천천히 한 발짝 다가간다.' },
    ],
  },
  {
    id: 'grass',
    name: '잎사귀요정',
    img: 'asset/monsters/grass_ally.png',
    devolvedImg: 'asset/monsters/grass_devolved.png',
    desc: '숲의 향기를 가진 수줍은 요정',
    hp: 28,
    maxHp: 28,
    xp: 0,
    xpThreshold: 5,
    inEgg: false,
    devolved: false,
    devolvedName: '씨앗눈',
    devolvedDesc: '눈처럼 작은 씨앗에서 눈이 반짝이는 존재',
    actions: [
      { id: 'forest_scent',  name: '숲 냄새',       axis: 'smell',    power: 12, escapeRisk: 2,  log: '은은한 숲 내음이 바람에 실려 온다.' },
      { id: 'hide',          name: '숨기기',        axis: 'behavior', power: 6,  escapeRisk: -8, log: '풀잎 뒤에 몸을 숨기며 위협을 줄인다.' },
      { id: 'soft_gesture',  name: '부드러운 몸짓', axis: 'smell',    power: 10, escapeRisk: 3,  log: '부드럽게 몸을 흔들며 향기를 퍼뜨린다.' },
    ],
  },
];

// Human bonding actions (2-3 types)
export const BONDING_ACTIONS = [
  {
    id: 'call_out',
    name: '부르기',
    desc: '조용한 목소리로 이름을 불러본다',
    type: 'voice',
    successBonus: 15,
    failPenalty: 12,
    log: {
      attempt: '조용히 이름을 불러본다...',
      success: '눈이 마주치고, 작게 고개를 끄덕인다!',
      fail: '경계하며 한 발짝 물러난다.',
    },
  },
  {
    id: 'sit_down',
    name: '앉기',
    desc: '천천히 앉아서 눈높이를 맞춘다',
    type: 'gesture',
    successBonus: 20,
    failPenalty: 8,
    log: {
      attempt: '천천히 무릎을 굽혀 앉는다...',
      success: '조심스럽게 다가와 곁에 머문다!',
      fail: '수상하다는 듯 고개를 갸웃거린다.',
    },
  },
  {
    id: 'hand_out',
    name: '손 내밀기',
    desc: '천천히 손을 내밀어 본다',
    type: 'gesture',
    successBonus: 25,
    failPenalty: 15,
    log: {
      attempt: '조심스럽게 손을 내민다...',
      success: '코를 손에 가만히 대고 냄새를 맡는다... 교감 성립!',
      fail: '깜짝 놀라 뒤로 물러선다!',
    },
  },
];

// Enemy monsters (8 types)
// preferences: positive = likes, negative = dislikes for each axis
// bondingPreference: which bonding type works best
export const ENEMY_MONSTERS = [
  {
    id: 'abyss_wolf',
    name: '심연 늑대',
    img: 'asset/monsters/enemy_abyss_wolf.png',
    desc: '어둠 속에서 눈만 빛나는 거대한 늑대',
    attackPower: 6,
    tamingThreshold: 70,
    escapeThreshold: 100,
    preferences: { sound: 1.5, temperature: 1.3, smell: 0.8, behavior: 0.6 },
    bondingPreference: 'gesture',
    reactions: {
      sound_good:   '귀가 빗소리 쪽으로 기울었다.',
      sound_bad:    '날카로운 소리에 으르렁거린다.',
      temp_good:    '따뜻함에 조금 몸을 풀었다.',
      temp_bad:     '추위에 털이 곤두선다.',
      smell_good:   '코를 킁킁거리며 냄새를 맡는다.',
      smell_bad:    '불쾌한 듯 코를 돌린다.',
      behav_good:   '경계를 조금 풀었다.',
      behav_bad:    '위협을 느끼고 이빨을 드러낸다.',
      attack:       '날카로운 발톱을 휘둘렀다!',
      calm:         '...조용히 바닥에 엎드렸다.',
    },
  },
  {
    id: 'glass_moth',
    name: '유리 나방',
    img: 'asset/monsters/enemy_glass_moth.png',
    desc: '투명한 날개가 달빛에 반짝이는 거대한 나방',
    attackPower: 4,
    tamingThreshold: 60,
    escapeThreshold: 80,
    preferences: { sound: 1.2, temperature: 0.7, smell: 1.0, behavior: 1.4 },
    bondingPreference: 'gesture',
    reactions: {
      sound_good:   '허밍에 맞춰 날개가 떨린다.',
      sound_bad:    '놀라 날개를 접었다.',
      temp_good:    '서늘함에 날개가 느리게 펄럭인다.',
      temp_bad:     '열기에 날개가 오그라든다.',
      smell_good:   '꽃향기 쪽으로 더듬이가 향한다.',
      smell_bad:    '강한 냄새에 날개를 감쌌다.',
      behav_good:   '조용한 태도에 살짝 가까이 왔다.',
      behav_bad:    '갑작스런 움직임에 높이 떴다.',
      attack:       '날카로운 비늘 가루를 뿌렸다!',
      calm:         '...천천히 날개를 접고 내려앉았다.',
    },
  },
  {
    id: 'stone_turtle',
    name: '바위 거북',
    img: 'asset/monsters/enemy_stone_turtle.png',
    desc: '등에 이끼가 자란 느린 거대 거북',
    attackPower: 8,
    tamingThreshold: 80,
    escapeThreshold: 120,
    preferences: { sound: 0.6, temperature: 1.0, smell: 1.5, behavior: 1.2 },
    bondingPreference: 'gesture',
    reactions: {
      sound_good:   '눈을 가늘게 뜨고 귀 기울인다.',
      sound_bad:    '등껍질 안으로 움츠러든다.',
      temp_good:    '따뜻함에 고개를 살짝 내밀었다.',
      temp_bad:     '추위에 더 깊이 들어갔다.',
      smell_good:   '이끼 냄새에 코를 벌름거린다.',
      smell_bad:    '역한 냄새에 고개를 돌렸다.',
      behav_good:   '느릿느릿 고개를 돌려 바라본다.',
      behav_bad:    '등껍질로 완전히 숨었다.',
      attack:       '무거운 몸을 들이밀었다!',
      calm:         '...편안히 고개를 내밀고 눈을 감았다.',
    },
  },
  {
    id: 'shadow_cat',
    name: '그림자 고양이',
    img: 'asset/monsters/enemy_shadow_cat.png',
    desc: '그림자처럼 일렁이는 검은 고양이',
    attackPower: 5,
    tamingThreshold: 55,
    escapeThreshold: 70,
    preferences: { sound: 0.9, temperature: 1.4, smell: 0.7, behavior: 1.3 },
    bondingPreference: 'voice',
    reactions: {
      sound_good:   '귀를 쫑긋 세우고 소리를 따라간다.',
      sound_bad:    '소리에 놀라 그림자 속으로 스며든다.',
      temp_good:    '따뜻한 곳에 몸을 웅크린다.',
      temp_bad:     '차가움에 털을 곤두세운다.',
      smell_good:   '냄새를 맡으며 고개를 갸웃.',
      smell_bad:    '불쾌한 듯 하악 소리를 낸다.',
      behav_good:   '경계하면서도 꼬리를 느리게 흔든다.',
      behav_bad:    '등을 활처럼 굽히며 경계한다.',
      attack:       '그림자 발톱을 날렸다!',
      calm:         '...그르릉, 작게 목을 울린다.',
    },
  },
  {
    id: 'crystal_deer',
    name: '수정 사슴',
    img: 'asset/monsters/enemy_crystal_deer.png',
    desc: '뿔이 수정처럼 빛나는 기품 있는 사슴',
    attackPower: 5,
    tamingThreshold: 65,
    escapeThreshold: 75,
    preferences: { sound: 1.4, temperature: 0.8, smell: 1.3, behavior: 0.9 },
    bondingPreference: 'voice',
    reactions: {
      sound_good:   '수정 뿔이 맑은 소리에 공명한다.',
      sound_bad:    '뿔의 빛이 날카롭게 번쩍인다.',
      temp_good:    '따뜻함에 코에서 하얀 김이 나온다.',
      temp_bad:     '추위에 발굽으로 땅을 찬다.',
      smell_good:   '숲 향기에 눈을 감고 들이마신다.',
      smell_bad:    '강한 냄새에 고개를 들어 올린다.',
      behav_good:   '조심스러운 태도에 발걸음을 멈추었다.',
      behav_bad:    '경계하며 뒷걸음친다.',
      attack:       '수정 뿔에서 빛이 쏟아진다!',
      calm:         '...천천히 고개를 숙이고 다가왔다.',
    },
  },
  {
    id: 'fog_jellyfish',
    name: '안개 해파리',
    img: 'asset/monsters/enemy_fog_jellyfish.png',
    desc: '공중에 떠다니는 반투명 해파리',
    attackPower: 3,
    tamingThreshold: 50,
    escapeThreshold: 65,
    preferences: { sound: 1.1, temperature: 1.5, smell: 0.5, behavior: 1.0 },
    bondingPreference: 'gesture',
    reactions: {
      sound_good:   '촉수가 소리에 맞춰 리듬을 탄다.',
      sound_bad:    '촉수를 바짝 움츠렸다.',
      temp_good:    '서늘함에 몸이 더 투명해졌다.',
      temp_bad:     '열기에 불안하게 떨린다.',
      smell_good:   '향기를 따라 천천히 떠온다.',
      smell_bad:    '냄새에서 멀어지며 높이 떠올랐다.',
      behav_good:   '가만히 있는 모습에 촉수를 늘어뜨렸다.',
      behav_bad:    '급한 움직임에 전기가 스파크친다.',
      attack:       '촉수에서 미약한 전기가 흐른다!',
      calm:         '...천천히 내려와 곁에 떠있다.',
    },
  },
  {
    id: 'iron_boar',
    name: '강철 멧돼지',
    img: 'asset/monsters/enemy_iron_boar.png',
    desc: '금속처럼 단단한 갈기를 세운 멧돼지',
    attackPower: 9,
    tamingThreshold: 85,
    escapeThreshold: 110,
    preferences: { sound: 0.5, temperature: 1.2, smell: 1.4, behavior: 0.8 },
    bondingPreference: 'voice',
    reactions: {
      sound_good:   '소리에 귀를 접고 잠시 멈추었다.',
      sound_bad:    '소음에 분노하며 발굽으로 땅을 찼다.',
      temp_good:    '따뜻함에 강철 갈기가 눕는다.',
      temp_bad:     '추위에 강철 갈기가 바짝 섰다.',
      smell_good:   '숲 냄새에 코를 땅에 대고 킁킁거린다.',
      smell_bad:    '자극적 냄새에 굉음을 내며 달려든다.',
      behav_good:   '다가가지 않자 조금 안심한 듯하다.',
      behav_bad:    '갑자기 다가오자 돌진 자세를 취한다.',
      attack:       '강철 갈기로 들이받았다!',
      calm:         '...거친 숨을 내쉬며 옆으로 누웠다.',
    },
  },
  {
    id: 'echo_bat',
    name: '메아리 박쥐',
    img: 'asset/monsters/enemy_echo_bat.png',
    desc: '초음파를 울리는 거대한 보라색 박쥐',
    attackPower: 4,
    tamingThreshold: 55,
    escapeThreshold: 70,
    preferences: { sound: 1.6, temperature: 0.6, smell: 0.9, behavior: 1.1 },
    bondingPreference: 'voice',
    reactions: {
      sound_good:   '소리를 따라 귀가 크게 펼쳐졌다.',
      sound_bad:    '날카로운 초음파를 쏘아 보낸다.',
      temp_good:    '서늘함에 날개를 접고 매달렸다.',
      temp_bad:     '열기에 불안하게 원을 그리며 난다.',
      smell_good:   '향기를 따라 낮게 날았다.',
      smell_bad:    '코를 찡그리며 높이 올라갔다.',
      behav_good:   '가만히 있자 거꾸로 매달려 관찰한다.',
      behav_bad:    '급한 동작에 날카롭게 울었다.',
      attack:       '초음파 파동을 내보냈다!',
      calm:         '...날개를 접고 조용히 매달려 있다.',
    },
  },
];

// Reaction log templates for generic situations
export const GENERIC_LOGS = {
  encounter: (name) => `야생 ${name}이(가) 나타났다!`,
  enemyAttack: (name, damage) => `${name}의 공격! ${damage}의 피해!`,
  allyFaint: (name) => `${name}이(가) 훈미 상태에 빠졌다...`,
  allFaint: '보유 몬스터가 모두 쓰러졌다... 게임 오버.',
  enemyEscape: (name) => `${name}이(가) 도망쳤다!`,
  tamingSuccess: (name) => `${name}과(와)의 교감에 성공했다!`,
  xpGain: (name, xp) => `${name}: 경험치 +1 (${xp})`,
  eggEnter: (name) => `${name}이(가) 알 상태에 들어갔다! 잠시 전투에 나설 수 없다.`,
  eggHatch: (name, newName) => `알에서 ${newName}이(가) 나왔다! ${name}이(가) 퇴화했다!`,
  bondingTooEarly: '아직 이르다... 순화가 더 필요하다.',
};
